export const GET_MOCK_DATA_REQUEST = 'GET_MOCK_DATA_REQUEST'
export type GET_MOCK_DATA_REQUEST = typeof GET_MOCK_DATA_REQUEST
export const GET_MOCK_DATA_SUCCESS = 'GET_MOCK_DATA_SUCCESS'
export type GET_MOCK_DATA_SUCCESS = typeof GET_MOCK_DATA_SUCCESS
export const GET_MOCK_DATA_ERROR = 'GET_MOCK_DATA_ERROR'
export type GET_MOCK_DATA_ERROR = typeof GET_MOCK_DATA_ERROR
